baseURL = 'https://blog.kaiv2.org/'
languageCode = 'zh-CN'
title = 'Kai'
theme = 'poison'

[params]
    brand = "Kai"
    description = "Kai's blog"
    dark_mode = false
    front_page_content = ["posts"] 
    menu = [
            {Name = "About", URL = "/about/", HasChildren = false},
            {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        ]
    github_url = "https://github.com/JavaHello"
    rss_icon = true
    rss_section = "posts"

